---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integrationcoexistencemanagment
  description: Microservicios para la consulta del permiso de la información del cliente/Microservicio Mapa Referencias/Microservicios para la configuración general de matriz de convivencia.
  tags:
    - microservice
    - permissions
  links:
    - url: https://github.com/JCAL0199/Integrationcoexistencemanagment
      title: Repository
  annotations:
    backstage.io/techdocs-ref: dir:.
    endpoints/dev: https://api.dev.company1.mx/company/1/nci-bdnsarintegrationcoexistencemanagment
    endpoints/qa: https://api.qa.company1.mx/company/1/nci-bdnsarintegrationcoexistencemanagment
    endpoints/prod: https://api.company1.mx/company/1/nci-bdnsarintegrationcoexistencemanagment
spec:
  type: service
  owner: group:default/juan-manuel-perez
  lifecycle: production
  system: bdnsar
  subcomponentOf: component:default/service-flask
